// Generated by shooosh. Do not edit.
export const fragment = "fn fsMain() -> vec4f {\n  let uv = fitUv(vUv);\n  let color = textureSample(uTexture, uSampler, uv);\n  if (uv.x < 0.0 || uv.x > 1.0 || uv.y < 0.0 || uv.y > 1.0) { return vec4f(0.0); }\n  return color;\n}";
export const fragmentGlsl = "#version 300 es\nprecision highp float;\nin vec2 vUv;\nuniform vec4 uUni[4];\nuniform sampler2D uTexture;\nout vec4 outColor;\nvec2 fitUv(vec2 uv) {\n  return uv * uUni[1].xy + uUni[1].zw;\n}\n\nvoid main() {\n  vec2 uv = fitUv(vUv);\n  vec4 color = texture(uTexture, uv);\n  if (uv.x < 0.0 || uv.x > 1.0 || uv.y < 0.0 || uv.y > 1.0) { outColor = vec4(0.0);\n  return; }\n  outColor = color;\n  return;\n\n}";
export default { fragment, fragmentGlsl };
